/** Natural words a user would type for each command category, per language. */
export const CATEGORY_LABELS: Record<string, { es: string; en: string }> = {
  accessibility: { es: 'accesibilidad', en: 'accessibility' },
  ai: { es: 'inteligencia artificial agentes', en: 'artificial intelligence agents' },
  api: { es: 'api endpoints', en: 'api endpoints' },
  automation: { es: 'automatización', en: 'automation' },
  cloud: { es: 'nube cloud', en: 'cloud' },
  'code-quality': { es: 'calidad de código revisión', en: 'code quality review' },
  content: { es: 'contenido redacción', en: 'content writing' },
  data: { es: 'datos analítica', en: 'data analytics' },
  database: { es: 'base de datos', en: 'database' },
  debugging: { es: 'depuración errores', en: 'debugging errors' },
  devops: { es: 'devops infraestructura', en: 'devops infrastructure' },
  docs: { es: 'documentación', en: 'documentation' },
  ecommerce: { es: 'tienda online comercio', en: 'ecommerce store' },
  finance: { es: 'finanzas', en: 'finance' },
  fullstack: { es: 'fullstack funcionalidades', en: 'fullstack features' },
  git: { es: 'git control de versiones', en: 'git version control' },
  i18n: { es: 'internacionalización traducción', en: 'internationalization translation' },
  legal: { es: 'legal contratos', en: 'legal contracts' },
  marketing: { es: 'marketing', en: 'marketing' },
  meta: { es: 'meta skills', en: 'meta skills' },
  ml: { es: 'aprendizaje automático', en: 'machine learning' },
  mobile: { es: 'móvil apps', en: 'mobile apps' },
  networking: { es: 'redes cloudflare', en: 'networking cloudflare' },
  observability: { es: 'observabilidad monitorización', en: 'observability monitoring' },
  performance: { es: 'rendimiento', en: 'performance' },
  product: { es: 'producto gestión', en: 'product management' },
  sales: { es: 'ventas', en: 'sales' },
  scaffold: { es: 'plantillas scaffolding', en: 'scaffolding templates' },
  security: { es: 'seguridad', en: 'security' },
  testing: { es: 'pruebas tests', en: 'testing tests' },
  utils: { es: 'utilidades', en: 'utilities' },
  web: { es: 'web interfaz', en: 'web ui' },
};
